apiVersion: v1
kind: Service
metadata:
  name: cars-service
spec:
  type: LoadBalancer
  selector:
    service: cars
  ports:
    - port: 5001
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      service: cars
  template:
    metadata:
      labels:
        service: cars
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: cars
          image: mbaleva/carrentingsystemcars:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80  