apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: LoadBalancer
  selector:
    service: identity
  ports:
    - port: 5002
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      service: identity
  template:
    metadata:
      labels:
        service: identity
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: identity
          image: mbaleva/carrentingsystemidentity:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80  