version: "3.9"

services:
  sqlserver:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - sqldata:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "myCoolPassword123#?!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    networks:
      carrentingsystem-network:

  rabbitmq:
    container_name: messaging
    image: rabbitmq:3
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=myCoolPassword123#?!
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    networks: 
      - carrentingsystem-network

  identity:
    container_name: identity
    image: mbaleva/carrentingsystemidentity:latest
    build: 
      dockerfile: "Servers/CarRentingSystem/CarRentingSystem.Identity/Dockerfile"
    ports:
      - "9000:80"
      - "9001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentingSystem.Identity;User Id=sa; Password=myCoolPassword123#?!;MultipleActiveResultSets=true
    restart: on-failure
    networks:
      - carrentingsystem-network
    depends_on: 
      - sqlserver

  cars:
    container_name: cars
    image: mbaleva/carrentingsystemcars:latest
    build: 
      dockerfile: "Servers/CarRentingSystem/CarRentingSystem.Cars/Dockerfile"
    ports:
      - "9002:80"
      - "9003:443"
    environment:
      - MessageBrokerSettings__Username=rabbitmquser
      - MessageBrokerSettings__Password=myCoolPassword123#?!
      - MessageBrokerSettings__Host=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentingSystem.Cars;User Id=sa; Password=myCoolPassword123#?!;MultipleActiveResultSets=true
    restart: on-failure
    networks:
      - carrentingsystem-network
    depends_on: 
      - sqlserver

  analyses:
    container_name: analyses
    image: mbaleva/carrentingsystemanalyses:latest
    build: 
      dockerfile: "Servers/CarRentingSystem/CarRentingSystem.Analyses/Dockerfile"
    ports:
      - "9004:80"
      - "9005:443"
    environment:
      - MessageBrokerSettings__Username=rabbitmquser
      - MessageBrokerSettings__Password=myCoolPassword123#?!
      - MessageBrokerSettings__Host=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentingSystem.Cars;User Id=sa; Password=myCoolPassword123#?!;MultipleActiveResultSets=true
    restart: on-failure
    networks:
      - carrentingsystem-network
    depends_on: 
      - sqlserver
  
  renting:
    container_name: renting
    image: mbaleva/carrentingsystemrenting:latest
    build: 
      dockerfile: "Servers/CarRentingSystem/CarRentingSystem.Renting/Dockerfile"
    ports:
      - "9006:80"
      - "9007:443"
    environment:
      - MessageBrokerSettings__Username=rabbitmquser
      - MessageBrokerSettings__Password=myCoolPassword123#?!
      - MessageBrokerSettings__Host=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentingSystem.Cars;User Id=sa; Password=myCoolPassword123#?!;MultipleActiveResultSets=true
    restart: on-failure
    networks:
      - carrentingsystem-network
    depends_on: 
      - sqlserver

  healthchecks:
        container_name: healthchecks
        image: mbaleva/carrentingsystemhealthchecks
        build:
            context: ./Server
            dockerfile: ./CarRentalSystem.HealthChecks/Dockerfile
        ports: 
            - "5500:80"
        environment:
            - HealthChecks-UI__HealthChecks__0__Name=Identity
            - HealthChecks-UI__HealthChecks__0__Uri=http://identity/health
            - HealthChecks-UI__HealthChecks__1__Name=Cars
            - HealthChecks-UI__HealthChecks__1__Uri=http://cars/health
            - HealthChecks-UI__HealthChecks__2__Name=Analyses
            - HealthChecks-UI__HealthChecks__2__Uri=http://analyses/health
            - HealthChecks-UI__HealthChecks__4__Name=Renting
            - HealthChecks-UI__HealthChecks__4__Uri=http://renting/health
        restart: on-failure
        networks: 
            - carrentingsystem-network
        depends_on:
            - identity
            - cars
            - analyses
            - renting
networks:
  carrentingsystem-network:

volumes:
  sqldata:
  rabbitmq: