version: "3.9"

services:
  sqlserver:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - sqldata:/var/opt/mssql
    ports:
      - "1433:1433"
    env_file:
      - ./.env/local/database-initial-config.local.env
    networks:
      carrentingsystem-network:

  rabbitmq:
    container_name: messaging
    image: rabbitmq:3
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    env_file:
      - ./.env/local/message-broker-initial-config.local.env
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    networks: 
      - carrentingsystem-network

  identity:
    container_name: identity
    image: mbaleva/carrentingsystemidentity:latest
    build: 
      dockerfile: "src/Servers/CarRentingSystem/CarRentingSystem.Identity/Dockerfile"
    ports:
      - "9000:80"
      - "9001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./.env/local/database-credentials.local.env
    restart: on-failure
    networks:
      - carrentingsystem-network
    depends_on: 
      - sqlserver

  cars:
    container_name: cars
    image: mbaleva/carrentingsystemcars:latest
    build: 
      dockerfile: "src/Servers/CarRentingSystem/CarRentingSystem.Cars/Dockerfile"
    ports:
      - "9002:80"
      - "9003:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./.env/local/database-credentials.local.env
      - ./.env/local/message-broker-settings.local.env
    restart: on-failure
    networks:
      - carrentingsystem-network
    depends_on: 
      - sqlserver

  analyses:
    container_name: analyses
    image: mbaleva/carrentingsystemanalyses:latest
    build: 
      dockerfile: "src/Servers/CarRentingSystem/CarRentingSystem.Analyses/Dockerfile"
    ports:
      - "9004:80"
      - "9005:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./.env/local/database-credentials.local.env
      - ./.env/local/message-broker-settings.local.env
    restart: on-failure
    networks:
      - carrentingsystem-network
    depends_on: 
      - sqlserver
  
  renting:
    container_name: renting
    image: mbaleva/carrentingsystemrenting:latest
    build: 
      dockerfile: "src/Servers/CarRentingSystem/CarRentingSystem.Renting/Dockerfile"
    ports:
      - "9006:80"
      - "9007:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./.env/local/database-credentials.local.env
      - ./.env/local/message-broker-settings.local.env
    restart: on-failure
    networks:
      - carrentingsystem-network
    depends_on: 
      - sqlserver

  updates:
    container_name: updates
    image: mbaleva/carrentingsystemupdates:latest
    build: 
      dockerfile: "src/Servers/CarRentingSystem/CarRentingSystem.UpdateService/Dockerfile"
    ports:
      - "9008:80"
      - "9009:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./.env/local/database-credentials.local.env
      - ./.env/local/message-broker-settings.local.env
    restart: on-failure
    networks:
      - carrentingsystem-network
    depends_on: 
      - sqlserver

  
  client:
    container_name: client
    image: mbaleva/carrentingsystemclient:latest
    build: 
      dockerfile: "src/Client/carrentingsystem/Dockerfile"
    ports:
      - "9010:80"
    restart: on-failure
    networks:
      - carrentingsystem-network
    depends_on: 
      - sqlserver

  healthchecks:
        container_name: healthchecks
        image: mbaleva/carrentingsystemhealthchecks
        build:
            dockerfile: ./src/Servers/CarRentingSystem/CarRentingSystem.HealthChecks/Dockerfile
        ports: 
            - "5500:80"
        env_file:
          - ./.env/local/health-checks-urls.local.env
        restart: on-failure
        networks: 
            - carrentingsystem-network
        depends_on:
            - identity
            - cars
            - analyses
            - renting
networks:
  carrentingsystem-network:

volumes:
  sqldata:
  rabbitmq: