version: "3.9"

services:
  sqlserver:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    volumes:
      - sqldata:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "myCoolPassword123#?!"
      ACCEPT_EULA: "Y"
    networks:
      carrentingsystem-network:

  rabbitmq:
    container_name: messaging
    image: rabbitmq:3
    ports:
      - "5672:5672"
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=myCoolPassword123#?!
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    networks: 
      - carrentingsystem-network

  identity:
    container_name: identity
    image: mbaleva/carrentingsystemidentity:latest
    build: 
      dockerfile: "./CarRentingSystem.Identity/Dockerfile"
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentingSystem.Identity;User Id=sa; Password=myCoolPassword123#?!;MultipleActiveResultSets=true
    restart: on-failure
    networks:
      - carrentingsystem-network
    depends_on: 
      - sqlserver

networks:
  carrentingsystem-network:

volumes:
  sqldata:
  rabbitmq: